// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM5xFCAJUGJw2MjnkhdmDCFhnk2PMYvd8',
    appId: '1:856284752906:web:a4fda76492baaa290543f3',
    messagingSenderId: '856284752906',
    projectId: 'skill-on-base',
    authDomain: 'skill-on-base.firebaseapp.com',
    storageBucket: 'skill-on-base.appspot.com',
    measurementId: 'G-GL5DJ26DJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwJeXB0tirZ3MC-jhn0ynx89f6-qRj-Fo',
    appId: '1:856284752906:android:b83b67a85ced756d0543f3',
    messagingSenderId: '856284752906',
    projectId: 'skill-on-base',
    storageBucket: 'skill-on-base.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALn2RUrYjQs1rINoJKAKN5F0RIHLEhmCU',
    appId: '1:856284752906:ios:26d049b9242ccd250543f3',
    messagingSenderId: '856284752906',
    projectId: 'skill-on-base',
    storageBucket: 'skill-on-base.appspot.com',
    iosBundleId: 'com.mobvers.skillOnBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALn2RUrYjQs1rINoJKAKN5F0RIHLEhmCU',
    appId: '1:856284752906:ios:63410511cd09ade10543f3',
    messagingSenderId: '856284752906',
    projectId: 'skill-on-base',
    storageBucket: 'skill-on-base.appspot.com',
    iosBundleId: 'com.mobvers.skillOnBase.RunnerTests',
  );
}
